In [164]:
                                                                  # FILE UPLOAD

from google.colab import files
uploaded = files.upload()

In [165]:
                                                                  # LIBRARIES IMPORT

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [166]:
personality_Data = pd.read_csv('personality_synthetic_dataset.csv')

In [167]:
personality_Data

,personality_type,social_energy,alone_time_preference,talkativeness,deep_reflection,group_comfort,party_liking,listening_skill,empathy,creativity,...,spontaneity,adventurousness,reading_habit,sports_interest,online_social_usage,travel_desire,gadget_usage,work_style_collaborative,decision_speed,stress_handling
0,Extrovert,6.794295,3.854670,8.725446,2.515151,7.097368,8.588762,6.774799,6.430132,6.142968,...,4.853313,8.257134,5.270555,10.000000,9.154296,4.816422,9.191711,8.313590,8.032376,7.176905
1,Ambivert,6.378988,5.731157,7.029529,7.274493,4.111199,3.258248,5.550909,3.958179,6.149457,...,6.067201,6.289347,5.753165,5.334303,4.683781,4.725666,5.956141,5.890619,3.158988,3.423577
2,Ambivert,7.459421,6.322263,3.922269,4.622261,5.343276,7.452152,9.483990,6.127654,7.032017,...,5.524244,9.238784,5.250405,3.153540,5.000338,6.139166,6.033048,5.807500,4.571003,5.647480
3,Extrovert,6.159626,3.097837,6.019093,1.965440,7.837140,10.000000,9.436733,8.949684,8.923875,...,4.327018,8.489791,5.312617,8.379936,7.601946,6.370056,5.410145,6.671781,6.600233,5.870088
4,Introvert,5.568462,6.986722,3.913240,9.926161,1.650483,0.362298,7.470387,6.756837,9.507803,...,5.187689,3.167217,7.060235,2.333388,7.771569,5.534336,5.704598,5.832968,5.813099,3.758084
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,Ambivert,3.783857,4.345803,8.220063,6.297798,5.162622,5.702266,5.518356,3.420139,5.811565,...,8.521256,4.355973,6.454815,2.557365,6.949292,4.176390,5.649897,5.665498,5.252077,4.297520
19996,Introvert,2.621406,8.152097,2.954341,8.791467,2.670252,2.931244,5.855202,5.044124,6.244061,...,4.818308,2.631298,10.000000,3.697801,3.217559,3.638815,5.177155,5.106628,0.982214,5.873321
19997,Introvert,0.039689,8.277160,5.728101,7.790080,3.427897,0.708457,7.099321,5.784592,5.400400,...,3.318511,4.071008,9.974147,2.954407,5.427296,6.270830,3.793430,5.009167,3.810962,5.678412
19998,Extrovert,7.756725,3.956191,8.906972,3.793775,7.608467,6.292705,6.824980,5.653421,7.347820,...,7.156525,8.148780,3.840900,6.093418,7.814507,8.428745,8.736932,8.060841,8.161087,5.941793
19999,Introvert,3.225794,8.058594,0.000000,10.000000,6.363376,0.242722,9.307219,7.621912,5.919581,...,5.097344,2.720616,7.344312,5.566736,6.350940,2.997643,5.991222,3.964673,1.967942,5.810435

In [168]:
                                      # SHAPE CHECK

personality_Data.shape

(20000, 30)

In [169]:
                                      # NULL VALUE CHECK

personality_Data.isnull().sum()

personality_type            0
social_energy               0
alone_time_preference       0
talkativeness               0
deep_reflection             0
group_comfort               0
party_liking                0
listening_skill             0
empathy                     0
creativity                  0
organization                0
leadership                  0
risk_taking                 0
public_speaking_comfort     0
curiosity                   0
routine_preference          0
excitement_seeking          0
friendliness                0
emotional_stability         0
planning                    0
spontaneity                 0
adventurousness             0
reading_habit               0
sports_interest             0
online_social_usage         0
travel_desire               0
gadget_usage                0
work_style_collaborative    0
decision_speed              0
stress_handling             0
dtype: int64

In [170]:
                                        # DUPLICATE CHECK

personality_Data.duplicated().sum()

np.int64(0)

In [171]:
                                          # 0 VALUE CHECK

(personality_Data==0).sum()

personality_type              0
social_energy               121
alone_time_preference       156
talkativeness               155
deep_reflection              18
group_comfort                33
party_liking                593
listening_skill               0
empathy                       0
creativity                    2
organization                  6
leadership                   30
risk_taking                 158
public_speaking_comfort     138
curiosity                     0
routine_preference           32
excitement_seeking          150
friendliness                  0
emotional_stability           0
planning                      3
spontaneity                  17
adventurousness             162
reading_habit                26
sports_interest              23
online_social_usage           2
travel_desire                30
gadget_usage                  1
work_style_collaborative      3
decision_speed               34
stress_handling               1
dtype: int64

In [172]:
                                # INFO CHECK ( data type, no nul counts )

personality_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   personality_type          20000 non-null  object
 1   social_energy             20000 non-null  float64
 2   alone_time_preference     20000 non-null  float64
 3   talkativeness             20000 non-null  float64
 4   deep_reflection           20000 non-null  float64
 5   group_comfort             20000 non-null  float64
 6   party_liking              20000 non-null  float64
 7   listening_skill           20000 non-null  float64
 8   empathy                   20000 non-null  float64
 9   creativity                20000 non-null  float64
 10  organization              20000 non-null  float64
 11  leadership                20000 non-null  float64
 12  risk_taking               20000 non-null  float64
 13  public_speaking_comfort   20000 non-null  float64
 14  curiosity                 20000 non-null  float64
 15  routine_preference        20000 non-null  float64
 16  excitement_seeking        20000 non-null  float64
 17  friendliness              20000 non-null  float64
 18  emotional_stability       20000 non-null  float64
 19  planning                  20000 non-null  float64
 20  spontaneity               20000 non-null  float64
 21  adventurousness           20000 non-null  float64
 22  reading_habit             20000 non-null  float64
 23  sports_interest           20000 non-null  float64
 24  online_social_usage       20000 non-null  float64
 25  travel_desire             20000 non-null  float64
 26  gadget_usage              20000 non-null  float64
 27  work_style_collaborative  20000 non-null  float64
 28  decision_speed            20000 non-null  float64
 29  stress_handling           20000 non-null  float64
dtypes: float64(29), object(1)
memory usage: 4.6+ MB

In [173]:
for col in personality_Data.columns :

  personality_Data[col]=personality_Data[col].replace(0,np.nan)

  if col == 'personality_type':

    continue

  skw = personality_Data[col].skew()


  if (skw > -1 and skw < 1):

    personality_Data[col] = personality_Data[col].fillna(personality_Data[col].mean())

  else :

    personality_Data[col] = personality_Data[col].fillna(personality_Data[col].median())

In [174]:
(personality_Data==0).sum()

personality_type            0
social_energy               0
alone_time_preference       0
talkativeness               0
deep_reflection             0
group_comfort               0
party_liking                0
listening_skill             0
empathy                     0
creativity                  0
organization                0
leadership                  0
risk_taking                 0
public_speaking_comfort     0
curiosity                   0
routine_preference          0
excitement_seeking          0
friendliness                0
emotional_stability         0
planning                    0
spontaneity                 0
adventurousness             0
reading_habit               0
sports_interest             0
online_social_usage         0
travel_desire               0
gadget_usage                0
work_style_collaborative    0
decision_speed              0
stress_handling             0
dtype: int64

In [175]:
personality_Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   personality_type          20000 non-null  object
 1   social_energy             20000 non-null  float64
 2   alone_time_preference     20000 non-null  float64
 3   talkativeness             20000 non-null  float64
 4   deep_reflection           20000 non-null  float64
 5   group_comfort             20000 non-null  float64
 6   party_liking              20000 non-null  float64
 7   listening_skill           20000 non-null  float64
 8   empathy                   20000 non-null  float64
 9   creativity                20000 non-null  float64
 10  organization              20000 non-null  float64
 11  leadership                20000 non-null  float64
 12  risk_taking               20000 non-null  float64
 13  public_speaking_comfort   20000 non-null  float64
 14  curiosity                 20000 non-null  float64
 15  routine_preference        20000 non-null  float64
 16  excitement_seeking        20000 non-null  float64
 17  friendliness              20000 non-null  float64
 18  emotional_stability       20000 non-null  float64
 19  planning                  20000 non-null  float64
 20  spontaneity               20000 non-null  float64
 21  adventurousness           20000 non-null  float64
 22  reading_habit             20000 non-null  float64
 23  sports_interest           20000 non-null  float64
 24  online_social_usage       20000 non-null  float64
 25  travel_desire             20000 non-null  float64
 26  gadget_usage              20000 non-null  float64
 27  work_style_collaborative  20000 non-null  float64
 28  decision_speed            20000 non-null  float64
 29  stress_handling           20000 non-null  float64
dtypes: float64(29), object(1)
memory usage: 4.6+ MB

In [176]:
personality_Data.describe()

,social_energy,alone_time_preference,talkativeness,deep_reflection,group_comfort,party_liking,listening_skill,empathy,creativity,organization,...,spontaneity,adventurousness,reading_habit,sports_interest,online_social_usage,travel_desire,gadget_usage,work_style_collaborative,decision_speed,stress_handling
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,...,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,5.542723,5.497571,5.569116,5.964056,6.024321,5.194067,6.964450,6.483220,5.996618,5.975072,...,5.499955,5.074822,5.948528,5.498813,6.499224,5.517211,6.007193,6.502961,5.525561,5.982281
std,2.430817,2.446381,2.439602,2.155018,2.164786,2.668901,1.647944,1.534911,1.495489,1.694432,...,1.916117,2.155875,2.160317,1.922716,1.888375,1.920245,1.682987,1.888103,1.930885,1.489726
min,0.001368,0.000102,0.003553,0.042981,0.013400,0.001683,1.308044,0.804853,0.754633,0.066264,...,0.002422,0.010053,0.034925,0.006021,0.168636,0.063628,0.022442,0.056492,0.006808,0.034922
25%,3.640515,3.571815,3.661029,4.390040,4.428815,3.005927,5.812701,5.448486,4.993084,4.807055,...,4.160591,3.494640,4.333478,4.135662,5.158811,4.166305,4.868130,5.161258,4.158214,4.973114
50%,5.542723,5.497571,5.574786,5.972345,6.051489,5.194067,6.989855,6.481365,6.003320,5.986871,...,5.499955,5.074822,5.962857,5.508153,6.528960,5.508014,6.007193,6.525735,5.528102,5.978713
75%,7.424123,7.416314,7.472371,7.598495,7.668598,7.363676,8.155574,7.521483,7.013412,7.142282,...,6.853083,6.656162,7.564929,6.861487,7.885414,6.877156,7.160525,7.878841,6.905844,6.991311
max,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [177]:
# DATA CLEANING DONE

In [178]:
                                          # I/p - o/p

X = personality_Data.drop(columns=['personality_type'])
y = personality_Data['personality_type']

In [179]:
X.shape

(20000, 29)

In [180]:
y.shape

(20000,)

In [181]:
                                          # DATA ENCODING ON y (O/p col)

from sklearn.preprocessing import LabelEncoder

In [182]:
le = LabelEncoder()
y=le.fit_transform(y)                     # y array me milega

In [183]:
print(le.classes_)

['Ambivert' 'Extrovert' 'Introvert']

In [184]:
# DATA ENCODING DONE

In [185]:
                                          # DATA SPLITTING

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [186]:
# Scaling not needed

In [187]:
                                            # MODEL CREATE -  LOGISTIC REGRESSION
'''
from sklearn.linear_model import LogisticRegression
'''

'\nfrom sklearn.linear_model import LogisticRegression\n'

In [188]:
'''log_reg_model = LogisticRegression()'''

'log_reg_model = LogisticRegression()'

In [189]:
'''log_reg_model.fit(X_train,y_train)'''

'log_reg_model.fit(X_train,y_train)'

In [190]:
'''log_reg_model_pred = log_reg_model.predict(X_test)'''

'log_reg_model_pred = log_reg_model.predict(X_test)'

In [191]:
                                            # evaluation

In [192]:
'''from sklearn.metrics import accuracy_score'''

'from sklearn.metrics import accuracy_score'

In [193]:
'''log_reg_acc_sc = accuracy_score(y_test,log_reg_model_pred)

log_reg_acc_sc      # -> 0.997'''

'log_reg_acc_sc = accuracy_score(y_test,log_reg_model_pred) \n\nlog_reg_acc_sc      # -> 0.997'

In [194]:
                  # CREATE MODEL - KNN

In [195]:
'''from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score'''

'from sklearn.neighbors import KNeighborsClassifier\n\nfrom sklearn.metrics import accuracy_score'

In [196]:
'''acc_sc_list = []
for i in range(1,11):

  knn_model = KNeighborsClassifier(n_neighbors=i)

  knn_model.fit(X_train,y_train)

  knn_model_pred = knn_model.predict(X_test)

  knn_acc_sc = accuracy_score(y_test,knn_model_pred)

  acc_sc_list.append(knn_acc_sc)

'''

'acc_sc_list = []\nfor i in range(1,11):\n\n  knn_model = KNeighborsClassifier(n_neighbors=i)\n\n  knn_model.fit(X_train,y_train)\n\n  knn_model_pred = knn_model.predict(X_test)\n\n  knn_acc_sc = accuracy_score(y_test,knn_model_pred)\n\n  acc_sc_list.append(knn_acc_sc)\n\n'

In [197]:
'''acc_sc_list'''

'acc_sc_list'

In [198]:
'''max_acc_sc = max(acc_sc_list)
print(max_acc_sc)'''

'max_acc_sc = max(acc_sc_list)\nprint(max_acc_sc)'

In [199]:
'''k_neighbor_val = acc_sc_list.index(max_acc_sc)
k_neighbor_val'''

'k_neighbor_val = acc_sc_list.index(max_acc_sc)\nk_neighbor_val'

In [200]:
                  # hyperparameter tuning

'''
knn_tuned_model = KNeighborsClassifier(n_neighbors=k_neighbor_val)

knn_tuned_model.fit(X_train,y_train)

knn_tuned_model_pred = knn_tuned_model.predict(X_test)

knn_tuned_acc_sc = accuracy_score(y_test,knn_tuned_model_pred)

knn_tuned_acc_sc              # -> 0.9975
'''

'                  \nknn_tuned_model = KNeighborsClassifier(n_neighbors=k_neighbor_val)\n\nknn_tuned_model.fit(X_train,y_train)\n\nknn_tuned_model_pred = knn_tuned_model.predict(X_test)\n\nknn_tuned_acc_sc = accuracy_score(y_test,knn_tuned_model_pred)\n\nknn_tuned_acc_sc              # -> 0.9975\n'

In [201]:
                            # MODEL CREATE - RANDOM FOREST CLASSIFIER

In [202]:
'''from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score'''

'from sklearn.ensemble import RandomForestClassifier\nfrom sklearn.metrics import accuracy_score'

In [203]:
'''ran_for_classif_model = RandomForestClassifier()'''

'ran_for_classif_model = RandomForestClassifier()'

In [204]:
'''ran_for_classif_model.fit(X_train,y_train)

ran_for_classif_model_pred = ran_for_classif_model.predict(X_test)
'''

'ran_for_classif_model.fit(X_train,y_train)\n\nran_for_classif_model_pred = ran_for_classif_model.predict(X_test)\n'

In [205]:
'''ran_for_classif_acc_sc = accuracy_score(y_test,ran_for_classif_model_pred)
ran_for_classif_acc_sc       # -> 0.9935'''

'ran_for_classif_acc_sc = accuracy_score(y_test,ran_for_classif_model_pred)\nran_for_classif_acc_sc       # -> 0.9935'

In [206]:
                                    # MODEL CREATE - SVM

from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

In [207]:
'''svm_linear_model = SVC(kernel='linear')
svm_linear_model.fit(X_train,y_train)
svm_linear_model_pred = svm_linear_model.predict(X_test)
'''

In [208]:
'''svm_linear_acc_sc = accuracy_score(y_test,svm_linear_model_pred)
svm_linear_acc_sc  # ->  0.997
'''

0.997

In [209]:
'''svm_poly_model = SVC(kernel='poly')

svm_poly_model.fit(X_train,y_train)

svm_poly_model_pred = svm_poly_model.predict(X_test)

svm_poly_acc_sc = accuracy_score(y_test,svm_poly_model_pred)

svm_poly_acc_sc      # -> 0.99725
'''

0.99725

In [210]:
'''svm_poly_model = SVC(kernel='rbf')

svm_poly_model.fit(X_train,y_train)

svm_poly_model_pred = svm_poly_model.predict(X_test)

svm_poly_acc_sc = accuracy_score(y_test,svm_poly_model_pred)

svm_poly_acc_sc      # -> 0.99725
'''

0.99775